### ISSUE TITLE
Ability to export `kube.Exporter` from a CLI utility

### ISSUE THREAD

**Issue by jlarfors** [volvo-cars/lingon#120]
For developing an operator I am using Lingon to store the sample kube manifests as Go code, instead of YAML.
These do not take any parameters, they are just simple samples that I could write in pure YAML.

It'd be nice to have a utility that could take a global `var` or call a function to create a `kube.Exporter` (i.e. an app) and generate the YAML for it.

Let's pretend this call is called `goky`:

```bash
goky -module=./pkg/whatever -func=NewApp

# Output is the YAML that is generated from call `whatever.NewApp()` and passing it to `kube.Export()`
# and sending it to stdout

# Then you can do
goky -module=./pkg/whatever -func=NewApp | kubectl apply -f -
```

**Comment by jlarfors** [comment]
The alternative I live with now is building a CLI that hardcodes the options for each manifest. It's definitely the "better" way to do it, but for something that is not prod/critical it'd be nice to have `goky`.

And I have no idea if that is even possible as I have not done any dynamic importing/processing of Go code in the past...

**Comment by jlarfors** [comment]
One option would be to use Go's plugin package: https://pkg.go.dev/plugin@go1.20.5

I could test this out as it might be more elegant than what I have already.

**Comment by veggiemonk** [comment]
There are no dynamic import in Go. 
The way to do it is:
A) generate a `main.go` containing the import for package and using `go run`
OR
B) generate a `xxx_test.go` with a test inside and running `go test`

**Comment by veggiemonk** [comment]
Personnaly, I use a tests and call the method `Export` which is custom for each `kube.App`.

**Comment by jlarfors** [comment]
> There are no dynamic import in Go.

Pretty sure I already knew this and paternity leave has left me optimistic/confused :D

Definitely the test approach is better and I went with that now.
A test takes care of the current working directory. I had a `cmd/gensamples/main.go` but the issue is that where you call it from makes a difference.
